/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Report {
  'id' : string,
  'title' : string,
  'content' : string,
  'date' : Time,
  'createdAt' : bigint,
  'author' : Principal,
  'lastUpdatedAt' : bigint,
  'timestamp' : Time,
  'hasVoiceTranscript' : boolean,
}
export interface ReportStatus {
  'userName' : string,
  'hasSubmittedToday' : boolean,
  'user' : Principal,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyReport' : ActorMethod<[Principal, bigint], [] | [Report]>,
  'getReportStatusForToday' : ActorMethod<[], Array<ReportStatus>>,
  'getReportsByDate' : ActorMethod<[bigint], Array<Report>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllReports' : ActorMethod<[], Array<Report>>,
  'listMyReports' : ActorMethod<[], Array<Report>>,
  'listReportsForToday' : ActorMethod<[], Array<Report>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDailyReport' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];