/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Time = IDL.Int;
export const Report = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'createdAt' : IDL.Int,
  'author' : IDL.Principal,
  'lastUpdatedAt' : IDL.Int,
  'timestamp' : Time,
  'hasVoiceTranscript' : IDL.Bool,
});
export const ReportStatus = IDL.Record({
  'userName' : IDL.Text,
  'hasSubmittedToday' : IDL.Bool,
  'user' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyReport' : IDL.Func(
      [IDL.Principal, IDL.Int],
      [IDL.Opt(Report)],
      ['query'],
    ),
  'getReportStatusForToday' : IDL.Func([], [IDL.Vec(ReportStatus)], ['query']),
  'getReportsByDate' : IDL.Func([IDL.Int], [IDL.Vec(Report)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'listMyReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'listReportsForToday' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDailyReport' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Time = IDL.Int;
  const Report = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'createdAt' : IDL.Int,
    'author' : IDL.Principal,
    'lastUpdatedAt' : IDL.Int,
    'timestamp' : Time,
    'hasVoiceTranscript' : IDL.Bool,
  });
  const ReportStatus = IDL.Record({
    'userName' : IDL.Text,
    'hasSubmittedToday' : IDL.Bool,
    'user' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyReport' : IDL.Func(
        [IDL.Principal, IDL.Int],
        [IDL.Opt(Report)],
        ['query'],
      ),
    'getReportStatusForToday' : IDL.Func(
        [],
        [IDL.Vec(ReportStatus)],
        ['query'],
      ),
    'getReportsByDate' : IDL.Func([IDL.Int], [IDL.Vec(Report)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'listMyReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'listReportsForToday' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDailyReport' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };